# Generated by Django 4.1 on 2022-11-11 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('price', models.FloatField()),
                ('phone', models.IntegerField(verbose_name='Contact Number')),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('admin_approval', models.BooleanField(default=False, max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='bh-images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.boardinghouse')),
            ],
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
