# Generated by Django 4.1 on 2023-01-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='created',
        ),
    ]
