# Generated by Django 4.1 on 2022-11-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0002_boardinghouse_remove_user_phone_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='phone',
            field=models.IntegerField(max_length=11, verbose_name='Contact Number'),
        ),
    ]
