# Generated by Django 4.1 on 2023-01-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
