# Generated by Django 4.1 on 2022-11-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0003_alter_boardinghouse_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='phone',
            field=models.FloatField(verbose_name='Contact Number'),
        ),
    ]
