# Generated by Django 4.1 on 2022-11-13 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0006_alter_boardinghouse_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1)], verbose_name='Contact Number'),
        ),
    ]
