# Generated by Django 4.1 on 2022-11-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0007_alter_boardinghouse_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Contact Number'),
        ),
    ]
