# Generated by Django 4.1 on 2022-12-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0009_alter_boardinghouse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='avail_room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
