# Generated by Django 4.1 on 2022-12-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0012_remove_boardinghouse_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='power',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
