# Generated by Django 4.1 on 2022-12-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0016_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
