# Generated by Django 4.1 on 2022-12-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0018_alter_user_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='created',
        ),
    ]
