# Generated by Django 4.1 on 2022-12-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0020_picture_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='created',
        ),
    ]
