# Generated by Django 4.1 on 2022-12-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0021_remove_picture_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
