# Generated by Django 4.1 on 2023-01-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0026_message_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
