# Generated by Django 4.1 on 2023-01-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0027_alter_message_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='session_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
