# Generated by Django 4.1 on 2023-01-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0028_alter_message_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='session_id',
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='My_App.session'),
            preserve_default=False,
        ),
    ]
