# Generated by Django 4.1 on 2023-01-01 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0030_alter_message_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(default=1, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='My_App.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
