# Generated by Django 4.1 on 2023-01-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0031_alter_message_session_alter_session_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='session',
            new_name='sessiond',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_id',
            new_name='session_ids',
        ),
    ]
