# Generated by Django 4.1 on 2023-01-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0032_rename_session_message_sessiond_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sessiond',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_ids',
            new_name='session_id',
        ),
    ]
