# Generated by Django 4.1 on 2023-01-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0033_rename_sessiond_message_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
