# Generated by Django 4.1 on 2023-01-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0035_alter_message_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='bh',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='My_App.boardinghouse'),
            preserve_default=False,
        ),
    ]
