# Generated by Django 4.1 on 2023-01-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0038_session_bh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='bh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My_App.boardinghouse'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
