# Generated by Django 4.1 on 2023-01-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0039_alter_session_bh_alter_session_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(blank=True, default=1, max_length=200, null=True, unique=True),
        ),
    ]
