# Generated by Django 4.1 on 2023-01-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0042_alter_message_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
