# Generated by Django 4.1 on 2023-01-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0045_remove_session_bh'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='bh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My_App.boardinghouse'),
        ),
    ]
