# Generated by Django 4.1 on 2022-10-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0047_alter_boardinghouse_picture1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
