# Generated by Django 4.1 on 2022-10-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0048_alter_boardinghouse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='picture4',
            field=models.FileField(blank=True, null=True, upload_to='bh-images/'),
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='picture5',
            field=models.FileField(blank=True, null=True, upload_to='bh-images/'),
        ),
    ]
