# Generated by Django 4.1 on 2022-10-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0049_boardinghouse_picture4_boardinghouse_picture5'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardinghouse',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
