# Generated by Django 4.1 on 2022-10-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0051_alter_boardinghouse_picture1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='picture1',
            field=models.FileField(blank=True, null=True, upload_to='bh-images/'),
        ),
    ]
