# Generated by Django 4.1 on 2022-10-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0052_alter_boardinghouse_picture1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardinghouse',
            old_name='picture1',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='boardinghouse',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='boardinghouse',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='boardinghouse',
            name='picture4',
        ),
        migrations.RemoveField(
            model_name='boardinghouse',
            name='picture5',
        ),
    ]
