# Generated by Django 4.1 on 2022-10-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0053_rename_picture1_boardinghouse_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardinghouse',
            name='picture',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='bh-images/')),
                ('bh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.boardinghouse')),
            ],
        ),
    ]
