# Generated by Django 4.1 on 2022-10-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0054_remove_boardinghouse_picture_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Picture',
        ),
    ]
