# Generated by Django 4.1 on 2022-10-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0057_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
